# test for ui

f.setTitle "Test App"
f.setViewWidth 400 height 400

f.setStyle "closebutton" width 30 height 30 textcolour "#f00" linecolour "#f00" fillcolour "#faa" align "centre"
f.setStyle "testbutton" width 300 height 25 textcolour "#0a0" linecolour "#0a0" fillcolour "#afa" align "left"

f.writeAs "tell" atX 10 atY 10 value " Tell" style "testbutton" onClickGoto :TELL
f.writeAs "choose" atX 10 atY 40 value " Choose" style "testbutton" onClickGoto :CHOOSE
f.writeAs "ask" atX 10 atY 70 value " Ask" style "testbutton" onClickGoto :ASK
f.writeAs "stop_timers" atX 10 atY 120 value "Stop All Timers" style "testbutton" onClickGoto :STOP_ALL
f.writeAs "exit" atX 365 atY 5 value "X" onClickGoto :EXIT style "closebutton"

f.onKey "escape" goto :ESC

# timer test
N = @ 0
TIMER_ON = @ 1
f.startTimerWithInterval 10 onTickGoto :TIMER_TEST

stop

:ASK
  platform.exec "ui" withArgs "ask -prompt \qYour Name\q -value Chris -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:CHOOSE
  platform.exec "ui" withArgs "choose -prompt \qChoose One\q -items \qhello/world/from/me\q -value 2 -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:TELL
  platform.exec "ui" withArgs "tell -prompt \qAbout\q -value \qui.exe// //(c)Cylexia\q -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:READ
  T = platform.readFromFile "test.txt"
  echo T
  stop
  
:FAIL
  f.writeAs "error" atX 0 atY 0 colour "#f00" value "Failed"
  stop

:EXIT
  f.exit
  stop



:TIMER_TEST
  N = increase N by 1
  DONE = testIf N = 10
  (DONE) f.stopTimer
  (DONE) TIMER_ON = @ 0
  f.setTitle N
  stop
  
:STOP_ALL
  TIMER_ON = @ 0
  f.stopTimer
  stop
  
:ESC
  (TIMER_ON) goto :STOP_ALL
  f.exit
  stop
