# test for ui

f.setTitle "Test App"
f.setViewWidth 400 height 400

f.writeAs "info" atX 10 atY 10 value "Info" onClickGoto :INFO
f.writeAs "choose" atX 10 atY 40 value "Choose" onClickGoto :CHOOSE
f.writeAs "ask" atX 10 atY 70 value "Ask" onClickGoto :ASK
f.writeAs "stop_timers" atX 10 atY 120 value "Stop All Timers" onClickGoto :STOP_ALL
f.writeAs "exit" atX 380 atY 5 value "[X]" onClickGoto :EXIT

f.onKey "escape" goto :ESC

# timer test
N = @ 0
TIMER_ON = @ 1
f.startTimer "title_timer" interval 10 onTickGoto :TIMER_TEST

stop

:ASK
  platform.exec "ui" withArgs "ask -prompt \qYour Name\q -value Chris -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:CHOOSE
  platform.exec "ui" withArgs "choose -prompt \qChoose One\q -items \qhello/world/from/me\q -value 2 -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:INFO
  platform.exec "ui" withArgs "info -prompt \qAbout\q -value \qui.exe|| ||(c)Cylexia\q -to test.txt" onDoneGoto :READ onErrorGoto :FAIL
  stop

:READ
  T = platform.readFromFile "test.txt"
  echo T
  stop
  
:FAIL
  f.writeAs "error" atX 0 atY 0 colour "#f00" value "Failed"
  stop

:EXIT
  f.exit
  stop



:TIMER_TEST
  N = increase N by 1
  DONE = testIf N = 10
  (DONE) f.stopTimer "title_timer"
  (DONE) TIMER_ON = @ 0
  f.setTitle N
  stop
  
:STOP_ALL
  TIMER_ON = @ 0
  f.stopAllTimers
  stop
  
:ESC
  (TIMER_ON) goto :STOP_ALL
  f.exit
  stop
